name: ipfs_sdk
version: 0.0.1
description: An IPFS Dart SDK to integrate with running IPFS instance
author: 'Tyrone Villaluna <tyrone.villaluna@proximax.io>'
homepage: https://www.proximax.io
repository: https://github.com/proximax-storage/dart-ipfs
issue_tracker: https://github.com/proximax-storage/dart-ipfs/issues
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
